# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: Bio
    url: /
    weight: 10
  - name: Research
    url: /#research
    weight: 20
  - name: Projects
    url: /#projects
    weight: 3
    parent: 'Research'
  - name: Publications
    url: /#publications
    weight: 1
    parent: 'Research'
  - name: Working Papers
    url: /#publications_selected
    weight: 2
    parent: 'Research'
  - name: Teaching
    url: /#teaching
    weight: 30
  - name: Miscellaneus
    url: ''
    weight: 60
    identifier: 'misc'
  - name: Talks
    url: /#talks
    weight: 3
    parent: 'misc'
  - name: Motivation
    url: \motiv
    weight: 4
    parent: 'misc'
    
    
    
